# This is a basic workflow to help you get started with Actions

name: clone workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            #ssh-keyscan -H github.com >> ~/.ssh/known_hosts # use this to avoid overwriting
            ssh-keyscan -H github.com > ~/.ssh/known_hosts
            git clone git@github.com:cmsc389T-spring22/Lecture6.git
